import { ActionType } from 'redux-promise-middleware';
export default {
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_PENDING: `CREATE_USER_${ActionType.Pending}`,
  CREATE_USER_FULFILLED: `CREATE_USER_${ActionType.Fulfilled}`,
  CREATE_USER_REJECTED: `CREATE_USER_${ActionType.Rejected}`,
  GET_USERS: 'GET_USERS',
  GET_USERS_PENDING: `GET_USERS_${ActionType.Pending}`,
  GET_USERS_FULFILLED: `GET_USERS_${ActionType.Fulfilled}`,
  GET_USERS_REJECTED: `GET_USERS_${ActionType.Rejected}`,
  FIND_USERS: 'FIND_USERS',
  FIND_USERS_PENDING: `FIND_USERS_${ActionType.Pending}`,
  FIND_USERS_FULFILLED: `FIND_USERS_${ActionType.Fulfilled}`,
  FIND_USERS_REJECTED: `FIND_USERS_${ActionType.Rejected}`,
  FIND_USER: 'FIND_USER',
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_PENDING: `DELETE_USER_${ActionType.Pending}`,
  DELETE_USER_FULFILLED: `DELETE_USER_${ActionType.Fulfilled}`,
  DELETE_USER_REJECTED: `DELETE_USER_${ActionType.Rejected}`,
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_PENDING: `UPDATE_USER_${ActionType.Pending}`,
  UPDATE_USER_FULFILLED: `UPDATE_USER_${ActionType.Fulfilled}`,
  UPDATE_USER_REJECTED: `UPDATE_USER_${ActionType.Rejected}`,
  FIND_USER: 'FIND_USER',
  FIND_USER_PENDING: `FIND_USER_${ActionType.Pending}`,
  FIND_USER_FULFILLED: `FIND_USER_${ActionType.Fulfilled}`,
  FIND_USER_REJECTED: `FIND_USER_${ActionType.Rejected}`,
};
